// <auto-generated />
namespace FruitBasketSimulator.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class cleanup31914 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cleanup31914));
        
        string IMigrationMetadata.Id
        {
            get { return "201403191813582_cleanup3.19.14"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
